// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moira.Backend.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moira.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(MoiraDbContext))]
    [Migration("20260927050245_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.CardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "star",
                            Meaning = "Esperança e renovação: um caminho mais leve se abre à sua frente.",
                            Name = "A Estrela"
                        },
                        new
                        {
                            Id = "strength",
                            Meaning = "Coragem serena para enfrentar o que pesa.",
                            Name = "A Força"
                        },
                        new
                        {
                            Id = "world",
                            Meaning = "Ciclo completo: aquilo que você buscou encontra realização.",
                            Name = "O Mundo"
                        });
                });

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.DrawEntity", b =>
                {
                    b.Property<string>("ReadingId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReadingId");

                    b.HasIndex("SessionId");

                    b.ToTable("draws", (string)null);
                });

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.DrawnCardEntity", b =>
                {
                    b.Property<string>("ReadingId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("ReadingId", "Order");

                    b.HasIndex("CardId");

                    b.ToTable("drawn_cards", (string)null);
                });

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.TemporaryUser", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.ToTable("temporary_users", (string)null);
                });

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.DrawEntity", b =>
                {
                    b.HasOne("Moira.Backend.Infrastructure.Entities.TemporaryUser", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.DrawnCardEntity", b =>
                {
                    b.HasOne("Moira.Backend.Infrastructure.Entities.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moira.Backend.Infrastructure.Entities.DrawEntity", null)
                        .WithMany("Cards")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Moira.Backend.Infrastructure.Entities.DrawEntity", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
