namespace Moira.Backend.Domain;

/// <summary>
/// Os 22 Arcanos Maiores. Textos originais da Moira, escritos para reflexão
/// (nunca previsão). Revisar com a curadoria de conteúdo antes do lançamento.
/// </summary>
public static class ArcanaCatalog
{
    public static readonly IReadOnlyList<ArcanaCard> MajorArcana =
    [
        new(0, "0", "O Louco", ["início", "confiança", "salto", "liberdade"],
            "A coragem de começar algo novo sem ter todas as respostas.",
            "A pressa de pular etapas só para fugir do desconforto.",
            "Que passo você daria se confiasse um pouco mais em si?"),
        new(1, "I", "O Mago", ["iniciativa", "habilidade", "foco", "vontade"],
            "Você já tem em mãos mais ferramentas do que imagina.",
            "Espalhar energia em muitas frentes ao mesmo tempo.",
            "Qual recurso seu está esperando para ser usado?"),
        new(2, "II", "A Sacerdotisa", ["intuição", "silêncio", "mistério", "escuta interior"],
            "Uma sabedoria interna que fala baixo, mas com clareza.",
            "Esperar certezas externas para validar o que você já sente.",
            "O que a sua intuição vem sussurrando e você ainda não ouviu?"),
        new(3, "III", "A Imperatriz", ["cuidado", "abundância", "criatividade", "acolhimento"],
            "Um tempo fértil para nutrir projetos, vínculos e a si mesma.",
            "Cuidar de todos e esquecer de receber cuidado também.",
            "Como seria cuidar de você com a mesma generosidade que cuida dos outros?"),
        new(4, "IV", "O Imperador", ["estrutura", "limites", "estabilidade", "decisão"],
            "Organizar, sustentar e colocar limites saudáveis.",
            "Rigidez que transforma segurança em controle.",
            "Que estrutura te daria mais tranquilidade agora?"),
        new(5, "V", "O Hierofante", ["tradição", "valores", "aprendizado", "pertencimento"],
            "Buscar orientação em valores e saberes que fazem sentido para você.",
            "Seguir regras que já não conversam com quem você é hoje.",
            "Quais valores você quer honrar nessa escolha?"),
        new(6, "VI", "Os Enamorados", ["escolha", "vínculo", "alinhamento", "afeto"],
            "Escolhas feitas a partir do que você realmente valoriza.",
            "Decidir para agradar, e não por alinhamento.",
            "Qual opção está mais alinhada com o seu coração e com os seus valores?"),
        new(7, "VII", "O Carro", ["movimento", "determinação", "direção", "avanço"],
            "Energia para seguir adiante com direção clara.",
            "Forçar o ritmo sem ouvir o próprio cansaço.",
            "Para onde você quer, de fato, conduzir esse momento?"),
        new(8, "VIII", "A Força", ["coragem gentil", "paciência", "autoconfiança", "domínio interior"],
            "Uma força que é firme sem precisar ser dura.",
            "Engolir sentimentos em nome de parecer forte.",
            "Onde você já é mais firme do que imagina?"),
        new(9, "IX", "O Eremita", ["introspecção", "pausa", "busca", "sabedoria"],
            "Um recolhimento que ilumina o que o barulho escondia.",
            "Isolar-se a ponto de se afastar do apoio que existe.",
            "O que você descobriria se desse a si um tempo de silêncio?"),
        new(10, "X", "A Roda da Fortuna", ["ciclos", "mudança", "movimento", "fluxo"],
            "Ciclos mudam, e a mudança também traz possibilidades.",
            "Sentir que nada depende de você.",
            "O que está ao seu alcance dentro deste ciclo?"),
        new(11, "XI", "A Justiça", ["equilíbrio", "verdade", "responsabilidade", "clareza"],
            "Olhar para os fatos com honestidade e equilíbrio.",
            "Ser dura demais no julgamento, inclusive consigo.",
            "Qual seria uma decisão justa com você e com os outros?"),
        new(12, "XII", "O Enforcado", ["nova perspectiva", "pausa", "entrega", "reavaliação"],
            "Mudar o ângulo de visão pode revelar outra saída.",
            "Ficar parada esperando que a situação se resolva sozinha.",
            "Como essa situação pareceria vista de outro ângulo?"),
        new(13, "XIII", "A Morte", ["transformação", "encerramento", "renovação", "passagem"],
            "O fim de uma fase que abre espaço para algo novo.",
            "Segurar o que já cumpriu o seu papel.",
            "O que está pronto para ser deixado para trás?"),
        new(14, "XIV", "A Temperança", ["equilíbrio", "paciência", "integração", "moderação"],
            "Combinar opostos com calma, no ritmo certo.",
            "Querer resolver tudo de uma vez.",
            "Onde um pouco mais de equilíbrio faria diferença?"),
        new(15, "XV", "O Diabo", ["apegos", "padrões", "desejo", "consciência"],
            "Reconhecer um padrão é o primeiro passo para se soltar dele.",
            "Justificar um hábito que já pesa mais do que ajuda.",
            "Que padrão você gostaria de olhar com mais honestidade?"),
        new(16, "XVI", "A Torre", ["ruptura", "revelação", "verdade", "reconstrução"],
            "Aquilo que desmorona às vezes libera espaço para o que é verdadeiro.",
            "Resistir a uma verdade que já apareceu.",
            "Que verdade, uma vez aceita, traria alívio?"),
        new(17, "XVII", "A Estrela", ["esperança", "cura", "inspiração", "fé"],
            "Esperança serena depois de um período difícil.",
            "Esperar sem também cuidar do que está ao seu alcance.",
            "O que renova a sua esperança hoje?"),
        new(18, "XVIII", "A Lua", ["intuição", "incerteza", "sonhos", "emoções profundas"],
            "Aceitar que nem tudo precisa estar claro para seguir.",
            "Deixar o medo preencher o que ainda não se sabe.",
            "O que é fato e o que é receio nessa história?"),
        new(19, "XIX", "O Sol", ["alegria", "vitalidade", "clareza", "autenticidade"],
            "Clareza e vitalidade para mostrar quem você é.",
            "Minimizar as próprias conquistas.",
            "O que te faz sentir viva e inteira?"),
        new(20, "XX", "O Julgamento", ["despertar", "chamado", "avaliação", "renascimento"],
            "Um chamado para rever a própria história com mais compaixão.",
            "Ficar presa a erros antigos.",
            "Que chamado interno você vem adiando?"),
        new(21, "XXI", "O Mundo", ["completude", "integração", "conquista", "ciclo fechado"],
            "Um ciclo importante se completando, com aprendizado integrado.",
            "Não reconhecer o quanto você já caminhou.",
            "O que você aprendeu que merece ser celebrado?"),
    ];

    public static ArcanaCard ByNumber(int number) =>
        number is >= 0 and <= 21
            ? MajorArcana[number]
            : throw new ArgumentOutOfRangeException(nameof(number), "Arcano inexistente.");
}
